/*
 * This source file was generated by the Gradle 'init' task
 */
package projeto.java;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static float somar(float a, float b){
        return a + b;
    }
}
